### ISSUE TITLE
Heroku button in README should only deploy stable versions

### ISSUE THREAD

**Issue by nkuehn** [sphereio/commercetools-sunrise-java#348]
The issue came up because a sales demo was deployed with known bugs. 

Heroku lets you point to a branch / tag in the button ( https://devcenter.heroku.com/articles/heroku-button#using-a-custom-git-branch ), but the issue is that the README would need to be updated with every release.  

If that's planned anyways, switching to [git flow](http://nvie.com/posts/a-successful-git-branching-model/) like done in the commercetools PHP ecosystem would solve the topic automatically as master would always equal "latest stable" (which would have advantages for other reasons, too, e.g. people naively cloning the repo and building projects on unstable versions).

**Comment by lauraluiz** [comment]
Thanks for the tip, I didn't see the template parameter before. I've created a stable tag and linked the Heroku button to that. It was really good timing since the master version is currently unstable in Heroku.

I'm planning on moving to a development branch, as it is quite important for Sunrise to have a stable master. Until I change the flow, I will change manually the Heroku button tag.
